name: particle-vtools
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - ipykernel
      - ipython
      - numpy
      - pandas
      - natsort
      - pyvista
      - matplotlib
      - imagecodecs
      - scikit-image
      - trame
      - ipywidgets
      - scikit-learn
      - trame-vtk
      - trame-vuetify
